# Generated by Django 4.2.13 on 2024-08-04 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_account', '0004_mpesamsg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('earnings_per_view', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_views', models.PositiveIntegerField()),
                ('duration_days', models.PositiveIntegerField(default=7)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images/')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='statuses/')),
                ('views', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
                ('earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whatsapp_rewards.package')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_account.useraccount')),
            ],
        ),
        migrations.CreateModel(
            name='UserHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected', models.BooleanField(default=False)),
                ('rejection_reason', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_by', to='user_account.useraccount')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whatsapp_rewards.status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_account.useraccount')),
            ],
        ),
    ]
