# Generated by Django 5.1.1 on 2024-09-25 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_profile', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Complaint',
        ),
    ]
