# Generated by Django 5.0.6 on 2024-07-14 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0002_useraccount_approved_useraccount_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='total_investments',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
