# Generated by Django 5.0.4 on 2024-08-05 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0004_mpesamsg'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='last_package_purchase',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='next_package_purchase_allowed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='package_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
