# Generated by Django 5.0.4 on 2024-08-06 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0005_useraccount_last_package_purchase_and_more'),
        ('whatsapp_rewards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='whatsapp_rewards.package'),
        ),
    ]
