# Generated by Django 5.1.1 on 2024-09-25 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0006_useraccount_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='usertransaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('investment', 'Investment')], max_length=20),
        ),
    ]
