# Generated by Django 5.1.1 on 2024-09-25 22:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0007_usertransaction_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='package',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package', models.CharField(choices=[('Silver', 'Silver Package - Ksh 1,000'), ('Iron', 'Iron Package - Ksh 3,000'), ('Bronze', 'Bronze Package - Ksh 5,000'), ('Gold', 'Gold Package - Ksh 10,000'), ('Bronze Pro', 'Bronze Pro Package - Ksh 20,000'), ('Gold Pro', 'Gold Pro Package - Ksh 50,000'), ('Exceptional', 'Exceptional Package - Ksh 100,000')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_invested', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InvestmentApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_approved', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_investments', to=settings.AUTH_USER_MODEL)),
                ('investment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_account.investment')),
            ],
        ),
    ]
