# Generated by Django 5.1.1 on 2024-09-26 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0008_alter_useraccount_package_investment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mpesamsg',
            options={},
        ),
        migrations.RemoveField(
            model_name='investment',
            name='date_invested',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='package',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='status',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='last_package_purchase',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='next_package_purchase_allowed',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='package',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='package_expiry',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='verified',
        ),
        migrations.RemoveField(
            model_name='usertransaction',
            name='status',
        ),
        migrations.RemoveField(
            model_name='usertransaction',
            name='verified',
        ),
        migrations.AddField(
            model_name='investment',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='investment',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='investment',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usertransaction',
            name='transaction_type',
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name='InvestmentApproval',
        ),
    ]
